language: erlang

sudo: false
os: linux
otp_release:
  - 23.0
  - 22.3
  - 21.3
  - 20.3
  - 19.3
  - 18.3
  - 17.5

script: epm eunit
install:
  - wget https://erl.pm/dl/epm && chmod +x epm
script:
  - ./epm as prod compile
  - ./epm xref
  - ./epm dialyzer
  - ./epm eunit
  - ./epm edoc

notifications:
  recipients:
    - hello@alind.io
